spring:
  application:
    name: nerve

  ai:
    google:
      genai:
        chat:
          options:
            model: gemini-3.1-flash-lite
        api-key: ${GEMINI_API_KEY}
    model:
      chat: google-genai


server:
  port: 8080

# Custom nerve config
nerve:
  memory:
    path: ./memory.json
  sandbox:
    path: /Users/yash/nerve-sandbox/workspace